version: '3.7'

services:
  app:
    restart: always
    image: prom/node-exporter:latest
    command:
      - --path.rootfs=/host
      - --collector.textfile.directory=/host/run/node-exporter
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'

  collectors:
    image: codemowers/prometheus-textfile-collectors:latest
    build:
      context: .
    restart: always
    network_mode: none
    privileged: true
    volumes:
      - '/dev:/dev'
      - '/sys:/sys:ro,rslave'
      - '/run/node-exporter:/run/node-exporter'

