version: '3.7'

services:
  app:
    restart: always
    image: prom/node-exporter:latest
    command:
      - --no-collector.fibrechannel
      - --no-collector.infiniband
      - --no-collector.tapestats
      - --no-collector.wifi
      - --collector.textfile.directory=/run/node-exporter
      - --collector.diskstats.ignored-devices=^(sr|loop)[0-9][0-9]*$
    network_mode: host
    pid: host
    volumes:
      - '/etc/os-release:/etc/os-release:ro'
      - '/sys:/sys:ro'
      - '/proc:/proc'
      - '/run/udev/data:/run/udev/data:ro'
      - '/run/node-exporter:/run/node-exporter:ro'

  collectors:
    image: codemowers/prometheus-textfile-collectors:latest
    build:
      context: .
    restart: always
    network_mode: none
    privileged: true
    volumes:
      - '/dev:/dev'
      - '/sys:/sys:ro,rslave'
      - '/run/node-exporter:/run/node-exporter'
